#!/usr/bin/env bash

ssh-keygen -t rsa

echo -n "Github Login: " && read GITUSER

curl -u "$GITUSER" https://api.github.com/user/keys\
     -d "{\"title\":\"`whoami`@`hostname` `date`\",\"key\":\"`cat $HOME/.ssh/id_rsa.pub`\"}"

git clone "git@github.com:$GITUSER/dotfiles.git" $HOME/dotfiles

$HOME/dotfiles/make.sh

